// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwenebhebfspowbsajsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3ZW5lYmhlYmZzcG93YnNhanNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzI0NTcsImV4cCI6MjA2MzcwODQ1N30.A9Fxs5iDdXRXwi9R9jnaXI7gnn9bVzzI340TMVULLRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);